# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on, and it will only run if it's not the GH Classroom bot
    if: ${{ github.actor != 'github-classroom[bot]' }}
    runs-on: ubuntu-latest

    permissions:
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Set Git config
        run: |
          git config user.email "test@test.com"
          git config user.name "GHClassroomBot"
      
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d - %H.%M.%S')"

      - name: Get last commit author
        id: commit_author
        run: echo "author=$(git log -1 --pretty=format:'%an')" >> $GITHUB_ENV

      - name: Save outputs to a file
        run: |
          
          echo "# Repository Info

          Please do not edit the contents of this file, it will be updated automatically via a GitHub Action each time you commit to this repo.
          Note: you will have to run `git pull` every time this happens to pull the most recent changes, this will also help you practice git commands!
          
          GitHub Username: ${{ github.actor }}
          
          Author: ${{ env.author }}

          Last Run Date: ${{ env.date }}
          
          Repository URL: ${{ github.server_url }}/${{ github.repository }}" > info.md
          git add . ; git commit -m "Initial commit of the template repo and an info file"; git push